### ISSUE TITLE
Is it possible to combine this order with another? 

### ISSUE THREAD

**Issue by Carpela** [panorama-ed/order_as_specified#17]
i.e. order_as_specified(status:Model::STATUSES, :updated_at)
So it orders by status first then by updated_At for the same status?

**Comment by JacobEvelyn** [comment]
Great question! You can achieve this behavior by chaining, like so: `Model.order_as_specified(status: Model::STATUSES).order(:updated_at)`

I'll add a note about this to the README.

**Comment by JacobEvelyn** [comment]
Just added a better README example along with a test for this behavior. Let me know if you have any questions!
