### ISSUE TITLE
Rails 5: private method `quote_value' called for #<Class:0x007fcc686c16a0>

### ISSUE THREAD

**Issue by sunef** [panorama-ed/order_as_specified#25]
Am getting this error: 

NoMethodError at /account/198/favorite-stores
private method `quote_value' called for #<Class:0x007fcc686c16a0>

I am using Rails 5, and I have put extend OrderAsSpecified under:

**client.rb**
Class Client < ApplicationRecord
  extend OrderAsSpecified
End

In my controller I have this: 

First I'm collecting User id's in an array: like [1,4,5,2]
**@favorites_collect_the_ids_in_array = @user.favorites.pluck(:client_id)**

Then I'm finding/creating an array based on those id's, to preserve the order from the array.
**index = Client.find(@favorites_collect_the_ids_in_array).group_by(&:id)**
 .. Mapping them into an array
**@array_of_all_favorites = @favorites_collect_the_ids_in_array.map { |i| index[i].first }**

Now I have an array of users in the same order [Client id: 1, Client id: 4, Client id: 6, Client id: 2]

Then I'm running the order_as_specified on it to turn it into an AR: 
So I'm putting the @array_of_all_favorites as :id:
**@ar_of_all_favorites = Client.order_as_specified(id: @array_of_all_favorites)**

And then I get the error.

I'd love to help out, but I'm not pro enough to contribute (yet) - Any suggestions?

**Comment by sunef** [comment]
Closing this. The error was that I should just do:

1: @favorites_collect_the_ids_in_array = @user.favorites.pluck(:client_id)

2: @ar_of_all_favorites = Client.order_as_specified(id: @favorites_collect_the_ids_in_array).where(id: @favorites_collect_the_ids_in_array)

**Comment by sunef** [comment]
Closing this. The error was that I should just do:

1: @favorites_collect_the_ids_in_array = @user.favorites.pluck(:client_id)

2: @ar_of_all_favorites = Client.order_as_specified(id: @favorites_collect_the_ids_in_array).where(id: @favorites_collect_the_ids_in_array)

**Comment by JacobEvelyn** [comment]
Glad to hear you figured it out! Thanks for the explanation.

**Comment by sunef** [comment]
Only issue now is: Should my first-born be named Jacob or Evelyn? This gem literally saved my life and tons of headaches, so thank you so much!

**Comment by JacobEvelyn** [comment]
Haha, glad to hear it's working well for you!
