### ISSUE TITLE
case insensitive ordering

### ISSUE THREAD

**Issue by stevenspiel** [panorama-ed/order_as_specified#29]
Feature request for the ability to order as specified without regard to casing

```rb
TestObject.order_as_specified(arel_table[:language].lower.in(["es", "en", "fr"]))
=> #<ActiveRecord::Relation [
     #<TestObject id: 3, language: "eS">,
     #<TestObject id: 1, language: "EN">,
     #<TestObject id: 4, language: "En">,
     #<TestObject id: 2, language: "fr">
   ]>
```

**Comment by JacobEvelyn** [comment]
Hey @stevenspiel! Thanks for the feature request. I'd love to hear a little more about this use case, as I'm not sure I can think of a scenario where I'd use it but I totally believe those scenarios are out there! What are you looking to do?

**Comment by JacobEvelyn** [comment]
@stevenspiel just wanted to reach out and see if you had more thoughts here?

**Comment by stevenspiel** [comment]
Oh, this was a long time ago. I don't remember the exact context. You can close it.
