### ISSUE TITLE
Using SELECT DISTINCT ON attribute

### ISSUE THREAD

**Issue by guyisra** [panorama-ed/order_as_specified#3]
using psql's DISTINCT ON requires the columns to be selected in the same order as the distinct

Since order_as_specified insert a new ORDER BY, I can't use  SELECT DISTINCT ON...

The only way I see is to use the same method for generating the order by, outside of the gem. 

Is there a way to use this gem with queries that involve DISTINCT ON?

**Comment by JacobEvelyn** [comment]
Great catch, @guyisra. Just to confirm I understand you correctly, you're trying to do something like:

`Person.order_as_specified(name: ["John", "Jane", "Jamie"]).select("DISTINCT ON (name) people.*")`

To give you one John, one Jane, and one Jamie, in that order, out of a set of potentially many Johns, Janes, and Jamies?

**Comment by JacobEvelyn** [comment]
If that's indeed the case, the trouble here is that this gem builds up queries that look like:

    ... ORDER BY people.first_name='John' DESC, people.first_name='Jane' DESC, people.first_name='Jamie' DESC

This means that it's actually ordering by a series of boolean expressions, so we need to `SELECT DISTINCT ON` those same expressions, like this:

    Person.order_as_specified(name: ["John", "Jane", "Jamie"]).select("DISTINCT ON (people.first_name='John', people.first_name='Jane', people.first_name='Jamie') people.*")

I'd be interested in supporting your use case better if we can come up with an API that makes sense. It seems like the options are:

- Add another method for this specific case, like `order_as_specified_distinct` that adds the `SELECT DISTINCT ON`.
- Expose a method that returns the boolean expressions, so it can be plugged in like `... .select("DISTINCT ON (#{select_distinct_on_expressions}) people.*").

The first option would be a bit nicer to use, while the second might be more flexible and a bit easier to implement. Thoughts, @guyisra and @seckenrode?

**Comment by guyisra** [comment]
Yes, my use case (which is why I am using distinct in the first place) is that I join some tables and then SELECT columns from the joined table, and not just from the original model table. So I have to distinct to avoid duplicity. 

Since order_as_specified inserts the ORDER I think it is best it would also, optionally, prepend that same order in the distinct.

Note the prepend, there might be situations where you would want to order by a none unique column and then order by some other criteria, so the order_as_specified ORDER would be first, and then the rest of the ORDER BY

what do you think?

**Comment by JacobEvelyn** [comment]
Just wanted to let you know that I haven't forgotten about this. I'm trying to figure out the best API for this, and I think it would probably be something akin to `order_as_specified(distinct_on: true, name: ["John", "Jane", "Jamie"])`. I'd rather not dive into your `ORDER` prepending proposal right now as the purpose of this gem really is to allow ordering by a specific list, not a specific list and then maybe other things. Adding multiple orderings also gets into the realm of changing the way `ActiveRecord` makes queries, which is a bit involved.

How does this sound @guyisra @seckenrode?

**Comment by kartikluke** [comment]
Came across the same issue with [Ransack](https://github.com/activerecord-hackery/ransack). In some cases the results from joins may return duplicate results. Hence a distinct is needed. Is there any progress on this.

The `order_as_specified(distinct_on: true, name: ["John", "Jane", "Jamie"])` method seems the most intuitive.

**Comment by JacobEvelyn** [comment]
Makes sense. I'll try to get this out this week.

**Comment by JacobEvelyn** [comment]
@kartikluke @guyisra this is out now in version 1.0. Let me know what you think!
