### ISSUE TITLE
Am getting the following error

### ISSUE THREAD

**Issue by harshamv** [panorama-ed/order_as_specified#5]
# NameError at /api/search

> uninitialized constant PlanMembership::OrderAsSpecified
## app/models/plan_membership.rb, line 2

``` ruby
    1   class PlanMembership < ActiveRecord::Base
>   2     extend OrderAsSpecified
    3     
    4     acts_as_paranoid
    5   
    6     belongs_to :plan, counter_cache: :memberships_count
    7     belongs_to :user
```

**Comment by JacobEvelyn** [comment]
Interesting. Do you get this if you add `require "order_as_specified"` at the top of the class?

**Comment by JacobEvelyn** [comment]
Looks like this was resolved. Closing.

**Comment by DianaEromosele** [comment]
hello, i'm also getting this error: 

NameError: uninitialized constant Politician::OrderAsSpecified

here's a bit of my Politician class:

class Politician < ActiveRecord::Base

	has_many :interests
	has_many :categories, through: :interests

	validates :name, :political_party, :title, :slug, presence: true

	extend FriendlyId
	friendly_id :name, use: :slugged

	extend OrderAsSpecified

**Comment by JacobEvelyn** [comment]
Hey @DianaEromosele! Sorry you're having trouble. As I noted above, do you get this error if you add `require "order_as_specified"` at the top of the class?

**Comment by JacobEvelyn** [comment]
Hey @MatthiasRMS! Would you be willing to share the code you're using? I wonder if you're either using `require "order_as_specified.rb"` instead of `require "order_as_specified"` or if when you deploy to Heroku your buildpack isn't running `bundle install`.

**Comment by MatthiasRMS** [comment]
Hmm I don't have the error anymore. Seems like I made a dumb mistake by switching branches. 
Seems to work fine using the Readme. 

Sorry for the trouble

**Comment by JacobEvelyn** [comment]
No worries, and glad to hear you figured it out!
