### ISSUE TITLE
Is it possible to implement NULLS FIRST/LAST options?

### ISSUE THREAD

**Issue by yfulmes** [panorama-ed/order_as_specified#61]
It would be helpful if you could specify nulls first or last options. So, It will separate null results from ELSE results.

**Comment by JacobEvelyn** [comment]
Hi @yfulmes! Great question. I see that we tried supporting `NULL`s in the list in the past, but according to our git history this didn't have good support across databases. It does appear to work in Postgres at least so I'll talk to our team and see if this is something we'd consider supporting for databases that can handle it.

**Comment by yfulmes** [comment]
Hi @JacobEvelyn. Thanks for the response. It would be great!

**Comment by JacobEvelyn** [comment]
Hi @yfulmes ! This feature is now released in version 1.7. You can include `NULL` values anywhere in your list (including first and last) like so:

```
TestObject.order_as_specified(language: ["es", nil, "fr"])
```

Hope that helps, and thanks for the suggestion!

**Comment by yfulmes** [comment]
Hi @JacobEvelyn. Many thanks to you! It's very helpful! Good luck!
